repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

releases:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard
    version: 7.13.0
    createNamespace: true
    wait: true
