# role for kauthproxy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubernetes-dashboard
  name: kauthproxy
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kubernetes-dashboard"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

---
# service account for end-to-end test
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: tester-token
  annotations:
    kubernetes.io/service-account.name: tester

---
# allow kauthproxy access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kubernetes-dashboard
  name: tester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kauthproxy
subjects:
  - kind: ServiceAccount
    namespace: default
    name: tester

---
# allow cluster read-only access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tester
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: default
    name: tester
