resources:
  # https://github.com/kubernetes/dashboard
  - https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
  # https://github.com/kubernetes-sigs/metrics-server
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml
  # Service account for end-to-end test
  - kauthproxy-role.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-1
        value: '--kubelet-insecure-tls'
