apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: auth-proxy
spec:
  homepage: https://github.com/int128/kauthproxy
  shortDescription: Authentication proxy to a pod or service
  description: |
    This is a kubectl plugin to forward a local port to a pod or service via the authentication proxy.
    It gets a token from the current credential plugin (e.g. aws-iam-authenticator or kubelogin).
    Then it appends the authorization header to HTTP requests, like `authorization: Bearer token`.
    All traffic is routed by the authentication proxy and port forwarder as follows:
      [browser] -> [authentication proxy] -> [port forwarder] -> [pod]

  caveats: |
    You need to configure authentication in the kubeconfig.
    See https://github.com/int128/kauthproxy for more.

  version: {{ .TagName }}
  platforms:
  - bin: kauthproxy
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_linux_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: amd64
  - bin: kauthproxy
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_linux_arm64.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm64
  - bin: kauthproxy
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_linux_arm.zip" .TagName }}
    selector:
      matchLabels:
        os: linux
        arch: arm
  - bin: kauthproxy
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_darwin_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: amd64
  - bin: kauthproxy
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_darwin_arm64.zip" .TagName }}
    selector:
      matchLabels:
        os: darwin
        arch: arm64
  - bin: kauthproxy.exe
    {{ addURIAndSha "https://github.com/int128/kauthproxy/releases/download/{{ .TagName }}/kauthproxy_windows_amd64.zip" .TagName }}
    selector:
      matchLabels:
        os: windows
        arch: amd64
