// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/int128/kauthproxy/pkg/cmd"
	"github.com/int128/kauthproxy/pkg/network"
	"github.com/int128/kauthproxy/pkg/portforwarder"
	"github.com/int128/kauthproxy/pkg/resolver"
	"github.com/int128/kauthproxy/pkg/reverseproxy"
	"github.com/int128/kauthproxy/pkg/usecases"
)

// Injectors from di.go:

func NewCmd() cmd.Interface {
	reverseProxy := &reverseproxy.ReverseProxy{}
	portForwarder := &portforwarder.PortForwarder{}
	factory := &resolver.Factory{}
	networkNetwork := &network.Network{}
	authProxy := &usecases.AuthProxy{
		ReverseProxy:    reverseProxy,
		PortForwarder:   portForwarder,
		ResolverFactory: factory,
		Network:         networkNetwork,
	}
	cmdCmd := &cmd.Cmd{
		AuthProxy: authProxy,
	}
	return cmdCmd
}
