// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/int128/kauthproxy/pkg/authproxy"
	"github.com/int128/kauthproxy/pkg/browser"
	"github.com/int128/kauthproxy/pkg/cmd"
	"github.com/int128/kauthproxy/pkg/env"
	"github.com/int128/kauthproxy/pkg/logger"
	"github.com/int128/kauthproxy/pkg/portforwarder"
	"github.com/int128/kauthproxy/pkg/resolver"
	"github.com/int128/kauthproxy/pkg/reverseproxy"
	"github.com/int128/kauthproxy/pkg/transport"
)

// Injectors from di.go:

func NewCmd() cmd.Interface {
	reverseProxy := &reverseproxy.ReverseProxy{}
	portForwarder := &portforwarder.PortForwarder{}
	loggerLogger := &logger.Logger{}
	factory := &resolver.Factory{
		Logger: loggerLogger,
	}
	newFunc := _wireNewFuncValue
	envEnv := &env.Env{}
	browserBrowser := &browser.Browser{}
	authProxy := &authproxy.AuthProxy{
		ReverseProxy:    reverseProxy,
		PortForwarder:   portForwarder,
		ResolverFactory: factory,
		NewTransport:    newFunc,
		Env:             envEnv,
		Browser:         browserBrowser,
		Logger:          loggerLogger,
	}
	cmdCmd := &cmd.Cmd{
		AuthProxy: authProxy,
		Logger:    loggerLogger,
	}
	return cmdCmd
}

var (
	_wireNewFuncValue = transport.NewFunc(transport.New)
)
