version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.15.8
    steps:
      - checkout

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            branches:
              only: dummy
            tags:
              only: dummy
