version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-sum-{{ checksum "go.sum" }}
      - run: make -C .circleci install-deps
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)
      - run: make dist
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi
      - save_cache:
          key: go-sum-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
