// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/int128/kauthproxy/internal/portforwarder (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination internal/mocks/mock_portforwarder/mock.go github.com/int128/kauthproxy/internal/portforwarder Interface
//

// Package mock_portforwarder is a generated GoMock package.
package mock_portforwarder

import (
	reflect "reflect"

	portforwarder "github.com/int128/kauthproxy/internal/portforwarder"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockInterface) Run(o portforwarder.Option, readyChan chan struct{}, stopChan <-chan struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", o, readyChan, stopChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockInterfaceMockRecorder) Run(o, readyChan, stopChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockInterface)(nil).Run), o, readyChan, stopChan)
}
