name: lint

on:
  push:
    paths:
      - .github/workflows/lint.yaml
      - '**.go'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38.0
