name: manifest

on:
  pull_request:
    branches:
      - master
    paths:
      - e2e_test/*.yaml
      - .github/workflows/manifest.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/manifest.yaml@v1.0.0
    permissions:
      contents: read
      pull-requests: write
    with:
      kustomization: |
        e2e_test/kustomization.yaml
