name: manifest

on:
  pull_request:
    branches: [master]
    paths:
      - e2e_test/*.yaml
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/hide-comment-action@v1
        with:
          ends-with: |
            <!-- kustomize-action -->
            <!-- diff-action -->
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: master
          path: master
      - uses: int128/kustomize-action@v1
        id: kustomize-head
        with:
          kustomization: e2e_test/kustomization.yaml
          write-individual-files: true
      - uses: int128/kustomize-action@v1
        id: kustomize-base
        with:
          base-directory: master
          kustomization: e2e_test/kustomization.yaml
          write-individual-files: true
      - uses: int128/diff-action@v1
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
