name: manifest

on:
  pull_request:
    branches: [master]
    paths:
      - e2e_test/*.yaml
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: int128/kustomize-action/diff@v1
        with:
          kustomization: e2e_test/kustomization.yaml
          write-individual-files: true
