name: manifest

on:
  pull_request:
    branches: [master]
    paths:
      - e2e_test/*.yaml
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: int128/kustomize-action/diff@v1
        with:
          kustomization: e2e_test/kustomization.yaml
          write-individual-files: true
